version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - database
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
